accounts/urls.py
from django.urls import path
from django.conf.urls.i18n import i18n_patterns
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView
from django.contrib import admin
from django.contrib.auth.views import (
     LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
)
from django.views.generic import TemplateView
# from telegram_bot.telegram_bot import set_webhook, webhook
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.admin.views.decorators import staff_member_required
from . import views
from .views import (
    AccountInactiveView,
    EmailView,
    EmailConfirmView,
    SignInView,
    SignupView,
    PasswordSetView,
    PasswordResetFromKeyView,
    PasswordResetFromKeyDoneView,
    PasswordChangeView,
    VIPView,
)


app_name = "accounts"  # добавьте это, если используете пространства имен

urlpatterns = [
    path( 'signup_closed/', TemplateView.as_view( template_name='signup_closed.html' ), name='signup_closed' ),
    path( 'logout/', LogoutView.as_view(), name='logout' ),
    path( 'verification_sent/', TemplateView.as_view( template_name='verification_sent.html' ),
          name='verification_sent' ),
    path( 'verified_email_required/', TemplateView.as_view( template_name='verified_email_required.html' ),
          name='verified_email_required' ),
    path( "account_inactive/", views.AccountInactiveView.as_view(), name="account_inactive" ),
    path( "email/", views.EmailView.as_view(), name="email" ),
    path( "email_confirm/", views.EmailConfirmView.as_view(), name="email_confirm" ),
    path( 'sign_in/', views.SignInView.as_view(), name='sign_in' ),
    path( 'signup/', views.SignupView.as_view(), name='signup' ),
    path( 'password_set/', views.PasswordSetView.as_view(), name='password_set' ),
    path( 'password_reset_from_key/', views.PasswordResetFromKeyView.as_view(), name='password_reset_from_key' ),
    path( 'password_reset_from_key_done/', views.PasswordResetFromKeyDoneView.as_view(),
          name='password_reset_from_key_done' ),
    path( 'password_change/', views.PasswordChangeView.as_view(), name='password_change' ),
    path( 'vip/', VIPView.as_view(), name='vip' ),
]

# urlpatterns = [
#     path('signup_closed/', TemplateView.as_view(template_name='signup_closed.html'), name='signup_closed'),
#     path('login/', LoginView.as_view(template_name='login.html'), name='login'),
#     path('logout/', LogoutView.as_view(), name='logout'),
#     path('verification_sent/', TemplateView.as_view(template_name='verification_sent.html'), name='verification_sent'),
#     path('verified_email_required/', TemplateView.as_view(template_name='verified_email_required.html'),
#          name='verified_email_required'),
#     path('password-reset/', PasswordResetView.as_view(template_name='password_reset.html'), name='password_reset'),
#     path('password-reset/done/', PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
#          name='password_reset_done'),
#     path('password-reset/confirm/<uidb64>/<token>/',
#          PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
#     path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
#          name='password_reset_complete'),
#     path( "account_inactive/", views.AccountInactiveView.as_view(), name="account_inactive" ),
#     path( "email/", views.EmailView.as_view(), name="email" ),
#     path( "email_confirm/", views.EmailConfirmView.as_view(), name="email_confirm" ),
#     path( 'sign_in/', views.SignInView.as_view(), name='sign_in' ),
#     path( 'signup/', views.SignupView.as_view(), name='signup' ),
#     path( 'password_set/', views.PasswordSetView.as_view(), name='password_set' ),
#     path( 'password_reset_from_key/', views.PasswordResetFromKeyView.as_view(), name='password_reset_from_key' ),
#     path( 'password_reset_from_key_done/', views.PasswordResetFromKeyDoneView.as_view(),
#           name='password_reset_from_key_done' ),
#     path( 'password_change/', views.PasswordChangeView.as_view(), name='password_change' ),
#     path( 'vip/', VIPView.as_view(), name='vip' ),
# ]
#    path( 'set_webhook/', set_webhook ),
#    path('webhook/', webhook, name='webhook'),
#    path('telegram_bot/', telegram_bot, name='telegram_bot'),

if settings.DEBUG:
    urlpatterns += static( settings.STATIC_URL, document_root=settings.STATIC_ROOT )
    # + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

art_event/urls.py
from django.urls import path
from django.conf.urls.i18n import i18n_patterns
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView
from django.contrib import admin

# from telegram_bot.views import webhook, telegram_bot
# from telegram_bot.telegram_bot import set_webhook, webhook
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.admin.views.decorators import staff_member_required
from . import views
from .views import Events_detail

app_name = "art_event"  # добавьте это, если используете пространства имен


urlpatterns = [
    path("articles/", views.ArticleListView.as_view(), name="articles"),
    path("articles/add/", views.add_article, name="add_article"),
    path(
        "articles/<int:pk>/update/",
        views.ArticleUpdateView.as_view(),
        name="update_article",
    ),
    path("events/", views.events, name="events"),
    path('events/<int:pk>/', Events_detail.as_view(), name='event_detail'),
    path("events/add/", views.EventCreateView.as_view(), name="add_event"),
    path(
        "events/<int:pk>/update/",
        views.EventUpdateView.as_view(),
        name="update_event",
    ),
    path(
        "events/<int:pk>/delete/",
        views.EventDeleteView.as_view(),
        name="delete_event",
    ),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

helpy/urls.py
from django.urls import path
from django.conf.urls.i18n import i18n_patterns
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView, TemplateView
from django.contrib import admin
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.admin.views.decorators import staff_member_required
from . import views
from .views import *

app_name = "helpy"  # добавьте это, если используете пространства имен


urlpatterns = [
    path("", index, name="index"),
    path("help/", views.search_helpers, name="help"),
    path("helpmy/", views.HelpMyView.as_view(), name="helpmy"),
    path("set_language/", RedirectView.as_view(url="/"), name="set_language"),
    path("helpers/", views.HelperListView.as_view(), name="helper_list"),
    path("helpers/add/", views.helper_form, name="add_helper"),
    path(
        "helpers/<int:pk>/update/",
        views.HelperUpdateView.as_view(),
        name="update_helper_info",
    ),
    path(
        "helpers/<int:pk>/delete/",
        views.HelperDeleteView.as_view(),
        name="delete_helper",
    ),
    path("about/", views.about, name="about"),
    path("donate/", views.donate_view, name="donate"),
    path('<str:helper_nickname>/', ChooseHelperView.as_view(), name='choose_helper'),
    path('help_thanks/', TemplateView.as_view(template_name='help_thanks.html'), name='help_thanks'),
    path("menu/", views.my_view, name="my_menu"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

helpySamui/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path("", RedirectView.as_view(pattern_name="helpy:index", permanent=False)),

    path("admin/", admin.site.urls),
    path("helpy/", include("helpy.urls")),
    path("offer/", include("offer.urls")),
    path("reviews/", include("reviews.urls")),
    path("accounts/", include("allauth.urls")),
    path("art_event/", include("art_event.urls")),
    path("accounts/", include("accounts.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# \
#    \
#     + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


# path('offer-help/', views.offer_help, name='offer_help'),
# path('telegram-bot/', views.telegram_bot, name='telegram_bot'),
# path('events/<int:pk>/', views.EventDetailView.as_view(), name='event_detail'),
# path('article/form/', ArticleFormView.as_view(), name='article_form'),path('addhelper', views.Helper),
# path('articles/', views.ArticleListView.as_view(), name='article_list'),
# path('articles/<int:pk>/', views.ArticleDetailView.as_view(), name='article_detail'),
# path('articles/create/', views.ArticleCreateView.as_view(), name='article_create'),
# path('articles/<int:pk>/update/', views.ArticleUpdateView.as_view(), name='article_update'),
# path('articles/<int:pk>/delete/', views.ArticleDeleteView.as_view(), name='article_delete'),
# path('events/', views.EventListView.as_view(), name='event_list'),
# path('events/<int:pk>/', views.EventDetailView.as_view(), name='event_detail'),
# path('events/create/', views.EventCreateView.as_view(), name='event_create'),
# path('events/<int:pk>/update/', views.EventUpdateView.as_view(), name='event_update'),
# path('events/<int:pk>/delete/', views.EventDeleteView.as_view(), name='event_delete'),
# path('helpers/', views.HelperListView.as_view(), name='helper_list'),
# path('helpers/<int:pk>/', views.HelperDetailView.as_view(), name='helper_detail'),
# path('helpers/create/', views.HelperCreateView.as_view(), name='helper_create'),
# path('helpers/<int:pk>/update/', views.HelperUpdateView.as_view(), name='helper_update'),
# path('helpers/<int:pk>/delete/', views.HelperDeleteView.as_view(), name='helper_delete'),
# path('events/', events, name='events'),

reviews/urls.py
from django.urls import path
from django.conf.urls.i18n import i18n_patterns
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView, CreateView
from django.contrib import admin
# from telegram_bot.views import webhook, telegram_bot
# from telegram_bot.telegram_bot import set_webhook, webhook
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.admin.views.decorators import staff_member_required
from .forms import ReviewForm_Art_Event
from .models import ReviewArt_Event
from .views import (
    review_helper,
    ReviewCreateView,
    review_edit,
    moderation_view,
    review_list_helper,
    review_detail, review_helper_edit, ReviewHelperEdit, ReviewCreateArt_Event, like, moderation_view,
)

app_name = "reviews"  # добавьте это, если используете пространства имен

urlpatterns = [
    path("reviews/review_helper/", review_helper, name="review_helper"),
    path( 'review_edit/<int:pk>/', review_edit, name='review_edit_Art_Event' ),
    path("reviews/add/", CreateView.as_view(model=ReviewArt_Event, form_class=ReviewForm_Art_Event),
         name="review-add_Art_Event"),
    path( "reviews/", review_list_helper, name="reviews_list" ),
    path("reviews/<int:pk>/", review_detail, name="review_detail"),
    path("reviews/moderate/",
        staff_member_required(moderation_view), name="moderation_view", ),
    path("<int:pk>/", review_detail, name="review_detail"),
    path("add/", ReviewCreateView.as_view(), name="reviews_add"),
    path("<int:pk>/edit/", ReviewHelperEdit, name="review_edit"),
    path('post/<int:pk>/like/', like, name='post_like'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT).as_view()

templates/base_templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en-US">
{% load i18n %}

  <head>
    <title>{% block title %}{% endblock %}</title>
      <link rel="stylesheet" href="{% static 'css/base.css' %}">
  </head>
  <body>
    {% include 'base_templates/header.html' %}

    <main>
      {% block content %}{% endblock %}
    </main>

    {% include 'base_templates/footer.html' %}

{#    <script src="{% static 'js/main.js' %}"></script>#}
  </body>
</html>

templates/base_templates/donate.html
{% extends 'base.html' %}

{% block content %}
  <h1>{% trans 'Поддержите нас' %}</h1>
  <p>{% trans 'Вы можете пожертвовать любую сумму, чтобы помочь нам развиваться и улучшать наши сервисы.' %}</p>
  <p>{% trans 'Спасибо за вашу поддержку!' %}</p>
{% endblock %}

templates/base_templates/footer.html
<footer>
  {% load i18n %}
    <div class="partners">
    <h4>{% trans "Our Partners:" %}</h4>
    <ul>
        {% for sponsor in sponsors %}
            <li><a href="{{ sponsor.url }}">{{ sponsor.name }}</a></li>
        {% endfor %}
    </ul>
</div>
  <div class="container">
   <p> &copy; ЮрийБелл2023. {% trans "All rights reserved." %} </p>
{# " language_code='en' http://dimasfrolov.com/  <a href="{% url 'index' %}" class="btn btn-primary">{% trans "Go back to the main page" language_code='en' %}</a>#}

  </div>

</footer>

templates/base_templates/header.html
{% load static %}
{% load bootstrap4 %}
{% load i18n %}

{% get_available_languages as LANGUAGES %}
{% get_current_language as CURRENT_LANGUAGE %}
{#{% {% load languages %} get_available_languages as LANGUAGES %}#}
{#{% get_current_language as CURRENT_LANGUAGE %}#}

<!DOCTYPE html>
<html lang="{{ CURRENT_LANGUAGE }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" type="image/png" href="{{ MEDIA_URL }}favicon.ico">
    <title>{% block title %}{% endblock %}</title>

{#    <link rel="stylesheet" href="{% static 'bootstrap4/css/bootstrap.min.css' %}"> #}
<link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">

<link rel="stylesheet" type="text/css" href="{% static 'bootstrap4/css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/header.css' %}">
    <script src="{% static 'jquery/jquery-3.6.3.min.js' %}"></script>
    <script src="{% static 'bootstrap4/js/bootstrap.min.js' %}"></script>
</head>
<body>
{#<label for="language-select">{% trans "Choose a language" %}:</label>#}
{#<select id="language-select">#}
{#{% for language in languages_with_flags %}#}
{#  <option value="{{ language.code }}" data-image="/static/flags/{{ language.flag }}.svg">{{ language.name }}</option>#}
{#{% endfor %}#}
{#</select>#}
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'helpy:index' %}">Helpy</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'helpy:helper_list' %}">Offer help</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'reviews:reviews_list' %}">Reviews</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:vip' %}">VIP</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'art_event:articles' %}">Articles</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'art_event:events' %}">Events</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'helpy:about' %}">About</a>
      </li>
    </ul>
  </div>
</nav>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
            {% for item in menu_items %}
                <li class="nav-item {% if item.title == current_view_name %}active{% endif %}">
                    <a class="nav-link" href="{{ item.url }}">{{ item.title }}</a>
                </li>
            {% endfor %}
        </ul>
    <!-- Вставьте этот код в шаблон перед циклом for menu_items -->
{#{% if menu_items %}#}
{#    <p>Menu items found: {{ menu_items|length }}</p>#}
{#{% else %}#}
{#    <p>No menu items found</p>#}
{#{% endif %}#}

    <ul class="navbar-nav ml-auto"> <!-- Add 'ml-auto' class here -->
        {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:logout' %}">{% trans "Logout" %}</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:sign_in' %}">{% trans "Login" %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:signup' %}">{% trans "Register" %}</a>
            </li>
        {% endif %}
    </ul>

</div>
  </nav>
<div class="container py-4">
    {% block content %}
    {% endblock %}
</div>
{% block scripts_bottom %}
{% endblock %}
<script>
  document.addEventListener('DOMContentLoaded', function() {
      const languageSelect = document.getElementById('language-select');
      languageSelect.addEventListener('change', function() {
          const selectedOption = this.options[this.selectedIndex];
          const flag = selectedOption.getAttribute('data-image');
          if (flag) {
        this.style.backgroundImage = 'url(' + flag + ')';
        this.classList.add('flag-icon');
      } else {
        this.style.backgroundImage = 'none';
        this.classList.remove('flag-icon');
      }
    });
    languageSelect.dispatchEvent(new Event('change'));
  });
</script>

</body>
</html>

templates/base_templates/success.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>{% trans "Success!" %}</h1>
        <p>{% trans "Your request has been successfully submitted." %}</p>
        <a href="{% url 'index' %}" class="btn btn-primary">{% trans "Home" %}</a>
      </div>
    </div>
  </div>
{% endblock %}