accounts/urls.py
from django.urls import path
from django.conf.urls.i18n import i18n_patterns
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView
from django.contrib import admin
from django.contrib.auth.views import (
     LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
)
from django.views.generic import TemplateView
# from telegram_bot.telegram_bot import set_webhook, webhook
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.admin.views.decorators import staff_member_required
from . import views
from .views import (
    AccountInactiveView,
    EmailView,
    EmailConfirmView,
    SignInView,
    SignupView,
    PasswordSetView,
    PasswordResetFromKeyView,
    PasswordResetFromKeyDoneView,
    PasswordChangeView,
    VIPView,
)


app_name = "accounts"  # добавьте это, если используете пространства имен

urlpatterns = [
    path( 'signup_closed/', TemplateView.as_view( template_name='signup_closed.html' ), name='signup_closed' ),
    path( 'logout/', LogoutView.as_view(), name='logout' ),
    path( 'verification_sent/', TemplateView.as_view( template_name='verification_sent.html' ),
          name='verification_sent' ),
    path( 'verified_email_required/', TemplateView.as_view( template_name='verified_email_required.html' ),
          name='verified_email_required' ),
    path( "account_inactive/", views.AccountInactiveView.as_view(), name="account_inactive" ),
    path( "email/", views.EmailView.as_view(), name="email" ),
    path( "email_confirm/", views.EmailConfirmView.as_view(), name="email_confirm" ),
    path( 'sign_in/', views.SignInView.as_view(), name='sign_in' ),
    path( 'signup/', views.SignupView.as_view(), name='signup' ),
    path( 'password_set/', views.PasswordSetView.as_view(), name='password_set' ),
    path( 'password_reset_from_key/', views.PasswordResetFromKeyView.as_view(), name='password_reset_from_key' ),
    path( 'password_reset_from_key_done/', views.PasswordResetFromKeyDoneView.as_view(),
          name='password_reset_from_key_done' ),
    path( 'password_change/', views.PasswordChangeView.as_view(), name='password_change' ),
    path( 'vip/', VIPView.as_view(), name='vip' ),
]

# urlpatterns = [
#     path('signup_closed/', TemplateView.as_view(template_name='signup_closed.html'), name='signup_closed'),
#     path('login/', LoginView.as_view(template_name='login.html'), name='login'),
#     path('logout/', LogoutView.as_view(), name='logout'),
#     path('verification_sent/', TemplateView.as_view(template_name='verification_sent.html'), name='verification_sent'),
#     path('verified_email_required/', TemplateView.as_view(template_name='verified_email_required.html'),
#          name='verified_email_required'),
#     path('password-reset/', PasswordResetView.as_view(template_name='password_reset.html'), name='password_reset'),
#     path('password-reset/done/', PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
#          name='password_reset_done'),
#     path('password-reset/confirm/<uidb64>/<token>/',
#          PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
#     path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
#          name='password_reset_complete'),
#     path( "account_inactive/", views.AccountInactiveView.as_view(), name="account_inactive" ),
#     path( "email/", views.EmailView.as_view(), name="email" ),
#     path( "email_confirm/", views.EmailConfirmView.as_view(), name="email_confirm" ),
#     path( 'sign_in/', views.SignInView.as_view(), name='sign_in' ),
#     path( 'signup/', views.SignupView.as_view(), name='signup' ),
#     path( 'password_set/', views.PasswordSetView.as_view(), name='password_set' ),
#     path( 'password_reset_from_key/', views.PasswordResetFromKeyView.as_view(), name='password_reset_from_key' ),
#     path( 'password_reset_from_key_done/', views.PasswordResetFromKeyDoneView.as_view(),
#           name='password_reset_from_key_done' ),
#     path( 'password_change/', views.PasswordChangeView.as_view(), name='password_change' ),
#     path( 'vip/', VIPView.as_view(), name='vip' ),
# ]
#    path( 'set_webhook/', set_webhook ),
#    path('webhook/', webhook, name='webhook'),
#    path('telegram_bot/', telegram_bot, name='telegram_bot'),

if settings.DEBUG:
    urlpatterns += static( settings.STATIC_URL, document_root=settings.STATIC_ROOT )
    # + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

helpy/urls.py
from django.urls import path
from django.conf.urls.i18n import i18n_patterns
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView, TemplateView
from django.contrib import admin
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.admin.views.decorators import staff_member_required
from . import views
from .views import *

app_name = "helpy"  # добавьте это, если используете пространства имен


urlpatterns = [
    path("", index, name="index"),
    path("help/", views.search_helpers, name="help"),
    path("helpmy/", views.HelpMyView.as_view(), name="helpmy"),
    path("set_language/", RedirectView.as_view(url="/"), name="set_language"),
    path("helpers/", views.HelperListView.as_view(), name="helper_list"),
    path("helpers/add/", views.helper_form, name="add_helper"),
    path(
        "helpers/<int:pk>/update/",
        views.HelperUpdateView.as_view(),
        name="update_helper_info",
    ),
    path(
        "helpers/<int:pk>/delete/",
        views.HelperDeleteView.as_view(),
        name="delete_helper",
    ),
    path("about/", views.about, name="about"),
    path("donate/", views.donate_view, name="donate"),
    path('<str:helper_nickname>/', ChooseHelperView.as_view(), name='choose_helper'),
    path('help_thanks/', TemplateView.as_view(template_name='help_thanks.html'), name='help_thanks'),
    path("menu/", views.my_view, name="my_menu"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

helpySamui/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path("", RedirectView.as_view(pattern_name="helpy:index", permanent=False)),

    path("admin/", admin.site.urls),
    path("helpy/", include("helpy.urls")),
    path("offer/", include("offer.urls")),
    path("reviews/", include("reviews.urls")),
    path("accounts/", include("allauth.urls")),
    path("art_event/", include("art_event.urls")),
    path("accounts/", include("accounts.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# \
#    \
#     + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


# path('offer-help/', views.offer_help, name='offer_help'),
# path('telegram-bot/', views.telegram_bot, name='telegram_bot'),
# path('events/<int:pk>/', views.EventDetailView.as_view(), name='event_detail'),
# path('article/form/', ArticleFormView.as_view(), name='article_form'),path('addhelper', views.Helper),
# path('articles/', views.ArticleListView.as_view(), name='article_list'),
# path('articles/<int:pk>/', views.ArticleDetailView.as_view(), name='article_detail'),
# path('articles/create/', views.ArticleCreateView.as_view(), name='article_create'),
# path('articles/<int:pk>/update/', views.ArticleUpdateView.as_view(), name='article_update'),
# path('articles/<int:pk>/delete/', views.ArticleDeleteView.as_view(), name='article_delete'),
# path('events/', views.EventListView.as_view(), name='event_list'),
# path('events/<int:pk>/', views.EventDetailView.as_view(), name='event_detail'),
# path('events/create/', views.EventCreateView.as_view(), name='event_create'),
# path('events/<int:pk>/update/', views.EventUpdateView.as_view(), name='event_update'),
# path('events/<int:pk>/delete/', views.EventDeleteView.as_view(), name='event_delete'),
# path('helpers/', views.HelperListView.as_view(), name='helper_list'),
# path('helpers/<int:pk>/', views.HelperDetailView.as_view(), name='helper_detail'),
# path('helpers/create/', views.HelperCreateView.as_view(), name='helper_create'),
# path('helpers/<int:pk>/update/', views.HelperUpdateView.as_view(), name='helper_update'),
# path('helpers/<int:pk>/delete/', views.HelperDeleteView.as_view(), name='helper_delete'),
# path('events/', events, name='events'),

accounts/models.py
# models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
# from art_event.models import Event, Article
from django.utils import timezone
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from helpySamui.constants import REGION_CHOICES, LANGUAGE_CHOICES, LEVEL_CHOICES


class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        """
        Создает и сохраняет пользователя с указанным email и паролем.
        """
        if not email:
            raise ValueError('Email обязателен для создания пользователя.')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        """
        Создает и сохраняет суперпользователя с указанным email и паролем.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(email, password, **extra_fields)

class MyUser(AbstractBaseUser, PermissionsMixin):
    social_networks = models.CharField( max_length=100, null=True, blank=True, default=None )
    email = models.EmailField(unique=True)
    userNick = models.CharField(max_length=255, unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True)
    category = models.CharField(
        max_length=255,
        choices=[("Helper", "Helper"), ("Customer", "Customer")],
        default="Customer",
    )
    district = models.ManyToManyField('Region')
    languages = models.ManyToManyField('Language')
    is_sponsor = models.BooleanField(default=False)
    phone_number = models.CharField(max_length=20, blank=True)
    about_me = models.TextField(blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = UserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.userNick

    def get_short_name(self):
        return self.userNick

    @property
    def is_authenticated(self):
        return True if self.id else False

    def has_perm(self, perm, obj=None):
        return self.is_superuser

    def has_module_perms(self, app_label):
        return self.is_superuser

class Sponsor(models.Model):
    name = models.CharField(max_length=255)
    url = models.URLField()

    def __str__(self):
        return self.name


class Region(models.Model):
    name = models.CharField(max_length=55, choices=REGION_CHOICES)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.pk:
            for choice in REGION_CHOICES:
                Region.objects.get_or_create(name=choice[1])
        super().save(*args, **kwargs)

class Language(models.Model):
    language = models.CharField(max_length=10, choices=LANGUAGE_CHOICES)

    def __str__(self):
        return self.language

    def save(self, *args, **kwargs):
        if not self.pk:
            for choice in LANGUAGE_CHOICES:
                Language.objects.get_or_create(language=choice[1])
        super().save(*args, **kwargs)

class SupportLevel(models.Model):
    level = models.IntegerField(choices=LEVEL_CHOICES)

    def __str__(self):
        return f"Level {self.level}"

    def save(self, *args, **kwargs):
        if not self.pk:
            for choice in LEVEL_CHOICES:
                SupportLevel.objects.get_or_create(level=choice[0])
        super().save(*args, **kwargs)

class Level(models.Model):
    level = models.IntegerField(choices=LEVEL_CHOICES)

    def __str__(self):
        return f"Level {self.level}"

    def save(self, *args, **kwargs):
        if not self.pk:
            for choice in LEVEL_CHOICES:
                Level.objects.get_or_create(level=choice[0])
        super().save(*args, **kwargs)


class Stats(models.Model):
    date = models.DateField(auto_now_add=True)
    active_helpers = models.IntegerField(default=0)
    help_requests = models.IntegerField(default=0)
    online_users = models.IntegerField(default=0)
    last_activity = models.ForeignKey(
        MyUser, on_delete=models.SET_NULL, null=True, blank=True
    )

    class Meta:
        verbose_name_plural = "Stats"

    def __str__(self):
        return f"{self.date} - Active helpers: {self.active_helpers}, Help requests: {self.help_requests}, Online users: {self.online_users}"

accounts/forms.py
from django import forms
# from django.contrib.auth.views import PasswordChangeView
from django.utils.translation import gettext_lazy as _
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
from django.contrib.auth import password_validation, get_user_model, authenticate
# from django.views.generic import CreateView
from .models import MyUser

class EmailForm(forms.Form):
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'})
    )
class CustomPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        label='Old password',
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password', 'autofocus': True}),
    )

    new_password1 = forms.CharField(
        label='New password',
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
        help_text=password_validation.password_validators_help_text_html(),
    )

    new_password2 = forms.CharField(
        label='Confirm new password',
        widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
    )

    class Meta:
        fields = ['old_password', 'new_password1', 'new_password2']

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = MyUser
        fields = ("email", "password1", "password2")

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['email'].label = "Email Address"

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

class EditVisitorProfileForm(forms.ModelForm):
    class Meta:
        model = MyUser
        fields = (
            "userNick",
            "category",
            "district",
            "languages",
            "phone_number",
            "email",
            "about_me",
        )


class AddEmailForm(forms.Form):
    email = forms.EmailField(label=_("Email address"))


class RemoveEmailForm(forms.Form):
    email = forms.EmailField(label=_("Email address to remove"))


class CustomAuthenticationForm(AuthenticationForm):
    email = forms.EmailField(widget=forms.TextInput(attrs={'autofocus': True}))
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password'}),
    )

    class Meta:
        model = MyUser
        fields = ["email", "password"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        del self.fields["username"]

    def clean(self):
        # Обновите аутентификацию, чтобы использовать email вместо username
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        if email is not None and password:
            self.user_cache = authenticate(self.request, email=email, password=password)
            if self.user_cache is None:
                raise self.get_invalid_login_error()
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data
class VisitorForm(forms.ModelForm):
    class Meta:
        model = MyUser
        fields = [
            "userNick",
            "category",
            "district",
            "languages",
            "is_sponsor",
            "phone_number",
            "email",
            ]
        widgets = {
            "district": forms.CheckboxSelectMultiple(),
            "languages": forms.CheckboxSelectMultiple(),
            # "favorites": forms.SelectMultiple(),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "post"
        self.helper.add_input(Submit("submit", "Save"))

templates/accounts/account_inactive.html
{% extends "base_templates/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Account Inactive" %}{% endblock %}

{% block content %}
<h1>{% trans "Account Inactive" %}</h1>

<p>{% trans "This djangoProject is inactive." %}</p>
{% endblock %}

templates/accounts/edit_visitor_profile.html
{% extends 'base_templates/base.html' %}

{% block content %}
  <h1>Edit Visitor Profile</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}

templates/accounts/email.html
{% extends "base_templates/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Account" %}{% endblock %}

{% block content %}
<h1>{% trans "E-mail Addresses" %}</h1>
{% if MyUser.email %}

<p>{% trans 'The following e-mail addresses are associated with your account:' %}</p>
<form action="{% url 'accounts:email' %}" class="email_list" method="post">
{% csrf_token %}
<fieldset class="blockLabels">
<div class="ctrlHolder">
      <label for="email_radio_1" class="primary_email">

  <input id="email_radio_1" type="radio" name="email" checked="checked" value="{{MyUser.email}}"/>
{{ MyUser.email }}
<span class="verified">{% trans "Verified" %}</span>
<span class="primary">{% trans "Primary" %}</span>
</label>

</div>
<div class="buttonHolder">
      <button class="secondaryAction" type="submit" name="action_send" >{% trans 'Re-send Verification' %}</button>
</div>
</fieldset>
</form>
{% else %}

<p><strong>{% trans 'Warning:'%}</strong> {% trans "You currently do not have any e-mail address set up. You should really add an e-mail address so you can receive notifications, reset your password, etc." %}</p>
{% endif %}

<h2>{% trans "Add E-mail Address" %}</h2>

<form method="post" action="{% url 'accounts:email' %}" class="add_email">
    {% csrf_token %}
    {{ visitor_form.as_p }}
    <button name="action_add" type="submit">{% trans "Add E-mail" %}</button>
</form>
{% endblock %}

{% block extra_body %}

<script type="text/javascript">
(function() {
  var message = "{% trans 'Do you really want to remove the selected e-mail address?' %}";
  var actions = document.getElementsByName('action_remove');
  if (actions.length) {
    actions[0].addEventListener("click", function(e) {
      if (! confirm(message)) {
        e.preventDefault();
      }
    });
  }
})();
</script>
{% endblock %}

templates/accounts/email_confirm.html
{% extends "base_templates/base.html" %}

{% load i18n %}

{% load crispy_forms_tags %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{% trans "Visitor Profile" %}</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit">{% trans "Save" %}</button>
  </form>
{% endblock %}

templates/accounts/login.html
{% extends "base_templates/base.html" %}
{% load i18n %}

{% block head_title %}{% trans "Sign In" %}{% endblock %}

{% block content %}

  <h1>{% trans "Sign In" %}</h1>
  <form class="login" method="POST" action="{% url 'accounts:sign_in' %}">
    {% csrf_token %}
    <label for="id_email">{% trans "Email" %}</label>
    <input type="email" name="email" id="id_email" placeholder="{% trans 'Email' %}" required autofocus>
<label for="id_password">{% trans "Password" %}</label>
<input type="password" name="password" id="id_password" placeholder="{% trans 'Password' %}" required>

{% if redirect_field_value %}
  <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
{% endif %}

<button class="primaryAction" type="submit">{% trans "Sign In" %}</button>
  </form>
{% endblock %}

templates/accounts/logout.html
{% extends "base_templates/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Sign Out" %}{% endblock %}

{% block content %}
<h1>{% trans "Sign Out" %}</h1>

<p>{% trans 'Are you sure you want to sign out?' %}</p>

<form method="post" action="{% url 'accounts:logout' %}">
  {% csrf_token %}
  {% if redirect_field_value %}
  <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
  {% endif %}
  <button type="submit">{% trans 'Sign Out' %}</button>
</form>


{% endblock %}

templates/accounts/password_change.html
{% extends "base_templates/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Change Password" %}{% endblock %}

{% block content %}
    <h1>{% trans "Change Password" %}</h1>

    <form method="POST" action="{% url 'accounts:password_change' %}" class="password_change">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" name="action">{% trans "Change Password" %}</button>
    </form>
{% endblock %}

templates/accounts/password_reset.html
{% extends "base_templates/base.html" %}

{% load i18n %}
{% load account %}

{% block head_title %}{% trans "Password Reset" %}{% endblock %}

{% block content %}

    <h1>{% trans "Password Reset" %}</h1>
    {% if user.is_authenticated %}
    {% include "accounts/snippets/already_logged_in.html" %}
    {% endif %}
<p>{% trans "Forgotten your password? Enter your e-mail address below, and we'll send you an e-mail allowing you to reset it." %}</p>

    <form method="POST" action="{% url 'accounts:password_reset' %}" class="password_reset">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="{% trans 'Reset My Password' %}" />
    </form>

    <p>{% blocktrans %}Please contact us if you have any trouble resetting your password.{% endblocktrans %}</p>
{% endblock %}

templates/accounts/password_reset_confirm.html
{% extends "base_templates/base.html" %}
{% load i18n %}

{% block head_title %}{% trans "Password Reset Confirmation" %}{% endblock %}

{% block content %}

  <h1>{% trans "Password Reset Confirmation" %}</h1>

  <form class="password-reset-confirm" method="POST" action="{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}">
    {% csrf_token %}
    <label for="id_new_password1">{% trans "New Password" %}</label>
    <input type="password" name="new_password1" id="id_new_password1" placeholder="{% trans 'New Password' %}" required autofocus>

    <label for="id_new_password2">{% trans "Confirm New Password" %}</label>
    <input type="password" name="new_password2" id="id_new_password2" placeholder="{% trans 'Confirm New Password' %}" required>

    <button class="primaryAction" type="submit">{% trans "Reset Password" %}</button>
  </form>

{% endblock %}

templates/accounts/password_reset_from_key.html
{% extends "base_templates/base.html" %}

{% load i18n %}
{% block head_title %}{% trans "Change Password" %}{% endblock %}

{% block content %}
    <h1>{% if token_fail %}{% trans "Bad Token" %}{% else %}{% trans "Change Password" %}{% endif %}</h1>

    {% if token_fail %}
        {% url 'accounts:password_reset' as passwd_reset_url %}
        <p>{% blocktrans %}The password reset link was invalid, possibly because it has already been used.  Please request a <a href="{{ passwd_reset_url }}">new password reset</a>.{% endblocktrans %}</p>
    {% else %}
        {% if form %}
            <form method="POST" action="{{ action_url }}">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" name="action" value="{% trans 'change password' %}"/>
            </form>
        {% else %}
            <p>{% trans 'Your password is now changed.' %}</p>
        {% endif %}
    {% endif %}
{% endblock %}

templates/accounts/password_reset_from_key_done.html
{% extends "base_templates/base.html" %}

{% load i18n %}
{% block head_title %}{% trans "Change Password" %}{% endblock %}

{% block content %}
    <h1>{% trans "Change Password" %}</h1>
    <p>{% trans 'Your password is now changed.' %}</p>
{% endblock %}

templates/accounts/signup.html
{% extends "base_templates/base.html" %}

{% load i18n %}

{% block content %}
  {% if form_type == 'signup' %}
    <h1>{% trans "Sign up" %}</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">{% trans "Sign up" %}</button>
    </form>
    <br>
    <p>{% trans "Already have an djangoProject?" %} <a href="{% url 'accounts:sign_in' %}">{% trans "Sign in" %}</a></p>
  {% elif form_type == 'login' %}
    <h1>{% trans "Sign in" %}</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">{% trans "Sign in" %}</button>
    </form>
    <br>
    <p>{% trans "Don't have an djangoProject yet?" %} <a href="{% url 'accounts:signup' %}">{% trans "Sign up" %}</a></p>
  {% endif %}
{% endblock %}

templates/accounts/signup_closed.html
{% extends "base_templates/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Sign Up Closed" %}{% endblock %}

{% block content %}
<h1>{% trans "Sign Up Closed" %}</h1>

<p>{% trans "We are sorry, but the sign up is currently closed." %}</p>
{% endblock %}

templates/accounts/verification_sent.html
{% extends "base_templates/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Verify Your E-mail Address" %}{% endblock %}

{% block content %}
    <h1>{% trans "Verify Your E-mail Address" %}</h1>

    <p>{% blocktrans %}We have sent an e-mail to you for verification. Follow the link provided to finalize the signup process. Please contact us if you do not receive it within a few minutes.{% endblocktrans %}</p>

{% endblock %}