accounts/urls.py
from django.urls import path
from django.conf.urls.i18n import i18n_patterns
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView
from django.contrib import admin
from django.contrib.auth.views import (
     LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
)
from django.views.generic import TemplateView
# from telegram_bot.telegram_bot import set_webhook, webhook
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.admin.views.decorators import staff_member_required
from . import views
from .views import (
    AccountInactiveView,
    EmailView,
    EmailConfirmView,
    SignInView,
    SignupView,
    PasswordSetView,
    PasswordResetFromKeyView,
    PasswordResetFromKeyDoneView,
    PasswordChangeView,
    VIPView,
)


app_name = "accounts"  # добавьте это, если используете пространства имен

urlpatterns = [
    path( 'signup_closed/', TemplateView.as_view( template_name='signup_closed.html' ), name='signup_closed' ),
    path( 'logout/', LogoutView.as_view(), name='logout' ),
    path( 'verification_sent/', TemplateView.as_view( template_name='verification_sent.html' ),
          name='verification_sent' ),
    path( 'verified_email_required/', TemplateView.as_view( template_name='verified_email_required.html' ),
          name='verified_email_required' ),
    path( "account_inactive/", views.AccountInactiveView.as_view(), name="account_inactive" ),
    path( "email/", views.EmailView.as_view(), name="email" ),
    path( "email_confirm/", views.EmailConfirmView.as_view(), name="email_confirm" ),
    path( 'sign_in/', views.SignInView.as_view(), name='sign_in' ),
    path( 'signup/', views.SignupView.as_view(), name='signup' ),
    path( 'password_set/', views.PasswordSetView.as_view(), name='password_set' ),
    path( 'password_reset_from_key/', views.PasswordResetFromKeyView.as_view(), name='password_reset_from_key' ),
    path( 'password_reset_from_key_done/', views.PasswordResetFromKeyDoneView.as_view(),
          name='password_reset_from_key_done' ),
    path( 'password_change/', views.PasswordChangeView.as_view(), name='password_change' ),
    path( 'vip/', VIPView.as_view(), name='vip' ),
]

# urlpatterns = [
#     path('signup_closed/', TemplateView.as_view(template_name='signup_closed.html'), name='signup_closed'),
#     path('login/', LoginView.as_view(template_name='login.html'), name='login'),
#     path('logout/', LogoutView.as_view(), name='logout'),
#     path('verification_sent/', TemplateView.as_view(template_name='verification_sent.html'), name='verification_sent'),
#     path('verified_email_required/', TemplateView.as_view(template_name='verified_email_required.html'),
#          name='verified_email_required'),
#     path('password-reset/', PasswordResetView.as_view(template_name='password_reset.html'), name='password_reset'),
#     path('password-reset/done/', PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
#          name='password_reset_done'),
#     path('password-reset/confirm/<uidb64>/<token>/',
#          PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
#     path('password-reset/complete/', PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
#          name='password_reset_complete'),
#     path( "account_inactive/", views.AccountInactiveView.as_view(), name="account_inactive" ),
#     path( "email/", views.EmailView.as_view(), name="email" ),
#     path( "email_confirm/", views.EmailConfirmView.as_view(), name="email_confirm" ),
#     path( 'sign_in/', views.SignInView.as_view(), name='sign_in' ),
#     path( 'signup/', views.SignupView.as_view(), name='signup' ),
#     path( 'password_set/', views.PasswordSetView.as_view(), name='password_set' ),
#     path( 'password_reset_from_key/', views.PasswordResetFromKeyView.as_view(), name='password_reset_from_key' ),
#     path( 'password_reset_from_key_done/', views.PasswordResetFromKeyDoneView.as_view(),
#           name='password_reset_from_key_done' ),
#     path( 'password_change/', views.PasswordChangeView.as_view(), name='password_change' ),
#     path( 'vip/', VIPView.as_view(), name='vip' ),
# ]
#    path( 'set_webhook/', set_webhook ),
#    path('webhook/', webhook, name='webhook'),
#    path('telegram_bot/', telegram_bot, name='telegram_bot'),

if settings.DEBUG:
    urlpatterns += static( settings.STATIC_URL, document_root=settings.STATIC_ROOT )
    # + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

helpy/urls.py
from django.urls import path
from django.conf.urls.i18n import i18n_patterns
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView, TemplateView
from django.contrib import admin
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.admin.views.decorators import staff_member_required
from . import views
from .views import *

app_name = "helpy"  # добавьте это, если используете пространства имен


urlpatterns = [
    path("", index, name="index"),
    path("help/", views.search_helpers, name="help"),
    path("helpmy/", views.HelpMyView.as_view(), name="helpmy"),
    path("set_language/", RedirectView.as_view(url="/"), name="set_language"),
    path("helpers/", views.HelperListView.as_view(), name="helper_list"),
    path("helpers/add/", views.helper_form, name="add_helper"),
    path(
        "helpers/<int:pk>/update/",
        views.HelperUpdateView.as_view(),
        name="update_helper_info",
    ),
    path(
        "helpers/<int:pk>/delete/",
        views.HelperDeleteView.as_view(),
        name="delete_helper",
    ),
    path("about/", views.about, name="about"),
    path("donate/", views.donate_view, name="donate"),
    path('<str:helper_nickname>/', ChooseHelperView.as_view(), name='choose_helper'),
    path('help_thanks/', TemplateView.as_view(template_name='help_thanks.html'), name='help_thanks'),
    path("menu/", views.my_view, name="my_menu"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

helpySamui/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path("", RedirectView.as_view(pattern_name="helpy:index", permanent=False)),

    path("admin/", admin.site.urls),
    path("helpy/", include("helpy.urls")),
    path("offer/", include("offer.urls")),
    path("reviews/", include("reviews.urls")),
    path("accounts/", include("allauth.urls")),
    path("art_event/", include("art_event.urls")),
    path("accounts/", include("accounts.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# \
#    \
#     + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


# path('offer-help/', views.offer_help, name='offer_help'),
# path('telegram-bot/', views.telegram_bot, name='telegram_bot'),
# path('events/<int:pk>/', views.EventDetailView.as_view(), name='event_detail'),
# path('article/form/', ArticleFormView.as_view(), name='article_form'),path('addhelper', views.Helper),
# path('articles/', views.ArticleListView.as_view(), name='article_list'),
# path('articles/<int:pk>/', views.ArticleDetailView.as_view(), name='article_detail'),
# path('articles/create/', views.ArticleCreateView.as_view(), name='article_create'),
# path('articles/<int:pk>/update/', views.ArticleUpdateView.as_view(), name='article_update'),
# path('articles/<int:pk>/delete/', views.ArticleDeleteView.as_view(), name='article_delete'),
# path('events/', views.EventListView.as_view(), name='event_list'),
# path('events/<int:pk>/', views.EventDetailView.as_view(), name='event_detail'),
# path('events/create/', views.EventCreateView.as_view(), name='event_create'),
# path('events/<int:pk>/update/', views.EventUpdateView.as_view(), name='event_update'),
# path('events/<int:pk>/delete/', views.EventDeleteView.as_view(), name='event_delete'),
# path('helpers/', views.HelperListView.as_view(), name='helper_list'),
# path('helpers/<int:pk>/', views.HelperDetailView.as_view(), name='helper_detail'),
# path('helpers/create/', views.HelperCreateView.as_view(), name='helper_create'),
# path('helpers/<int:pk>/update/', views.HelperUpdateView.as_view(), name='helper_update'),
# path('helpers/<int:pk>/delete/', views.HelperDeleteView.as_view(), name='helper_delete'),
# path('events/', events, name='events'),

offer/urls.py
from django.urls import path
from django.conf.urls.i18n import i18n_patterns
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView
from django.contrib import admin
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.admin.views.decorators import staff_member_required
from . import views

app_name = "offer"  # добавьте это, если используете пространства имен


urlpatterns = [
    path("admin/", admin.site.urls),
    path("helpers/", views.HelperListView.as_view(), name="helper_list"),
    path("helpers/add/", views.helper_form, name="add_helper"),
    path(
        "helpers/<int:pk>/update/",
        views.HelperUpdateView.as_view(),
        name="update_helper_info",
    ),
    path(
        "helpers/<int:pk>/delete/",
        views.HelperDeleteView.as_view(),
        name="delete_helper",
    ),
    path("success/", views.success, name="success"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

offer/models.py
# models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from accounts.models import SupportLevel, Region, Language
from helpy.models import Tag_help

class Helper(models.Model):
    USER_TYPE_CHOICES = (
        ("helper", "Помощник"),
        ("customer", "Клиент"),
    )
    name = models.CharField(max_length=255)
    vip = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag_help)
    support_levels = models.ManyToManyField(SupportLevel)
    regions = models.ManyToManyField(Region)
    contacts = models.TextField()
    user_offer_is_free = models.BooleanField(default=False)
    languages = models.ManyToManyField(Language)
    email = models.EmailField(max_length=255, blank=True, null=True)
    soft_skills = models.TextField(blank=True, null=True)
    phone = models.CharField(max_length=255, blank=True, null=True)

offer/views.py
# views.py
from datetime import date
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.admin.views.decorators import staff_member_required
from django.core.paginator import Paginator
from django.db.models import Count, Q
from django.forms import ModelForm
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.utils.translation import gettext as _
from django.views import View
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from django.views.generic.edit import FormView
from django_countries import countries
from accounts.models import MyUser
from .decorators import admin_only
from .forms import LanguageForm, RegionForm, Tag_helpForm, SupportLevelForm, HelpForm, HelpRequestForm, HelperCreateForm, HelperUpdateForm
from .models import Helper

from helpy.forms import *
from helpy.models import *

from .my_menu import *

@login_required
class CreateHelper(CreateView):
    model = Helper
    form_class = HelperCreateForm
    template_name = "offer/helper_form.html"
    success_url = reverse_lazy("helper_profile")

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.user_type = "helper"
        messages.success(
            self.request, _("Your helper data has been created successfully.")
        )
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, _("Please correct the errors below."))
        return super().form_invalid(form)


def add_tag(request):
    if request.method == "POST":
        form = Tag_helpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("tags_list")
    else:
        form = Tag_helpForm()

    context = {"form": form}

    # Если форма не прошла валидацию, добавляем в контекст список ошибок
    if form.errors:
        context["errors"] = form.errors

    return render(request, "offer/helper_form.html", context)


def helper_form(request):
    if request.method == "POST":
        form = HelperCreateForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Helper added successfully!")
            return redirect("offer:success")
    else:
        form = HelperCreateForm()
    return render(request, "helper_form.html", {"form": form})


def success(request):
    return render(request, "offer/success.html")


def language_form(request):
    if request.method == "POST":
        form = LanguageForm(request.POST)
        if form.is_valid():
            languages = form.cleaned_data["languages"]
            for language in languages:
                Language.objects.create(language=language)
            return redirect("helper_form")
    else:
        form = LanguageForm()
    return render(request, "offer/helper_form.html", {"form": form})



# Классы-представления для помощников (Helper)
class HelperListView(ListView):
    model = Helper
    template_name = "offer/helper_list.html"
    context_object_name = "helpers"


class HelperDeleteView(LoginRequiredMixin, DeleteView):
    model = Helper
    success_url = reverse_lazy("helper_list")
    template_name = "offer/helper_confirm_delete.html"

    def get_object(self):
        return get_object_or_404(Helper, pk=self.kwargs["pk"], user=self.request.user)

class HelperUpdateView(LoginRequiredMixin, UpdateView):
    model = Helper
    form_class = HelperUpdateForm
    template_name = "offer/update_helper.html"
    success_url = reverse_lazy("helper_profile")

    def get_object(self):
        return get_object_or_404(Helper, pk=self.kwargs["pk"], user=self.request.user)

    def form_valid(self, form):
        messages.success(
            self.request, "Your helper data has been updated successfully."
        )
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Please correct the errors below.")
        return super().form_invalid(form)

templates/offer/helper_confirm_delete.html
{% extends 'base_templates/base.html' %}
{% load i18n %}
{% block content %}
  <h1>{% trans "Deleting profile" %}</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.confirm.label_tag }}
    {{ form.confirm }}
    <br>
    <button type="submit" class="btn btn-danger">{% trans "Delete" %}</button>
    <a href="{% url 'helper_list' object.pk %}" class="btn btn-secondary">{% trans "Cancel" %}</a>
  </form>
{% endblock %}

templates/offer/helper_form.html
{% extends 'base_templates/base.html' %}
{% load i18n %}
{% load static %}
{% comment %}
шаблон для того чтобы добавить данные помощника
{% endcomment %}
{% block content %}
  <h1>{% trans 'Adding helper' %}</h1>
<p> %} <a href="{% url 'accounts:vip' %}">{% trans 'Click here to get VIP status and enjoy additional privileges.'%} </a> </p>
    <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {{ field }}
      </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary">{% trans 'Add helper' %}</button>
  </form>
{% endblock %}

templates/offer/helper_list.html
{% extends 'base_templates/base.html' %}
{% load i18n %}

{% comment %}
шаблон для выбора добавить, обновить или удалить данные помощника
{% endcomment %}

{% block content %}
  {% if user.is_authenticated %}
    <p>
<h1>{% trans "Would you like to help people and earn extra income? Join our team, find friends with similar interests, improve your abilities, and add your skills and talents to our database. You can edit your information, set a 'ready to help now' flag to increase your visibility in search results, or delete your data from our database. Fill out a simple form to find a rewarding job that fits you!" %} </h1>

    <p>{% trans "We are grateful that you share our mission - to help people. Please choose the aspects and level of possible help and enter them into our Database. Your information is only displayed when a user searches for a helper." %}</p>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <a href="{% url 'offer:add_helper' %}">
        <button type="button">{% trans "Add Helper" %}</button>
      </a>
      <br>
      {% if user.helper %}
        <p>{% trans "If you are already in our Database, we suggest updating your information." %}</p>
        <a href="{% url 'offer:update_helper_info' user.helper.pk %}">
          <button>{% trans "Edit My Data" %}</button>
        </a>
      {% endif %}
      <br>
      {% if user.helper %}
        <p>{% trans "If you want to remove your data from our Database, please click the button below." %}</p>
        <a href="{% url 'offer:delete_helper' user.helper.pk %}">
          <button>{% trans "Delete My Data" %}</button>
        </a>
      {% endif %}
    </form>
  {% else %}
    <p>
      {% trans "Please" %}
      <a href="{% url 'accounts:signup' %}" class="btn btn-primary">{% trans "register" %}</a>
      {% trans "or" %}
      <a href="{% url 'accounts:sign_in' %}" class="btn btn-secondary">{% trans "login" %}</a>
      {% trans "to add yourself to our list of helpers." %}
    </p>
  {% endif %}
{% endblock %}

templates/offer/offer_help.html
{% extends "base_templates/base.html" %}
{% load i18n %}

{% comment %} {% load helpers %}
шаблон на случай если я решу использовать поиск по помощникам. пока концепция этого не предумсматиривает
{% endcomment %}

{% block content %}
    <h1>{% trans "Offer help" %}</h1>

    <form action="{% url 'search_helpers' %}" method="get">
        <label for="search">{% trans "Search helpers" %}:</label>
        <input type="text" id="search" name="search">
        <button type="submit">{% trans "Search" %}</button>
    </form>
    <br>
    <a href="{% url 'add_helper' %}">{% trans "Add a new helper" %}</a>
    <br>
    <form action="{% url 'search_helpers' %}" method="get">
        <label for="tags">{% trans "Tags" %}:</label>
        <input type="text" id="tags" name="tags">
        <button type="submit">{% trans "Search" %}</button>
    </form>
    <br>
    <div>
        {% trans "Tags:" %}
        {% for tag in tags %}
            <a href="{% url 'search_helpers' %}?tag={{ tag }}">{{ tag }}</a>
        {% endfor %}
    </div>
    <br>
    {% if helpers %}
        {% for row in helpers|batch:3 %}
            <div class="row">
                {% for helper in row %}
                    <div class="col">
                        <a href="{% url 'view_helper' helper.id %}">
                            {{ helper.name }}
                        </a>
                        {% for tag in helper.tags.all %}
                            <span class="tag">{{ tag.name }}</span>
                        {% endfor %}
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
        <br>
        <div>
            {% if helpers.has_previous %}
                <a href="?page={{ helpers.previous_page_number }}">{% trans "Previous" %}</a>
            {% endif %}
            <span class="current-page">{% trans "Page" %} {{ helpers.number }}/{{ helpers.paginator.num_pages }}</span>
            {% if helpers.has_next %}
                <a href="?page={{ helpers.next_page_number }}">{% trans "Next" %}</a>
            {% endif %}
        </div>
    {% else %}
        <p>{% trans "No helpers found." %}</p>
    {% endif %}
{% endblock %}

templates/offer/success.html
{% extends 'base_templates/base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
  <div class="alert alert-success" role="alert">
    {% trans "Helper added or updated successfully!" %}
  </div>
  <a href="{% url 'offer:helper_list' %}" class="btn btn-primary">{% trans 'Back to helper list' %}</a>
{% endblock %}

templates/offer/update_helper.html
{% extends 'base_templates/base.html' %}
{% comment %}
шаблон для того чтобы обновить данные помощника
{% endcomment %}

{% load i18n %}

{% block content %}
  <h1>{% trans 'Update' %} {% trans 'Helper Data' %}</h1>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <label for="{{ field.id_for_label }}">{{ field.label }}</label>
      <input type="{{ field.field.widget.input_type }}" name="{{ field.name }}" id="{{ field.id_for_label }}" value="{{ field.value|default:'' }}" {% if field.field.required %}required{% endif %}><br>
    {% endfor %}
    <button type="submit">{% trans 'Update' %}</button>
  </form>
{% endblock %}